import { supabaseAdmin } from '@/lib/supabaseAdmin';
const TELEGRAM_BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN;const BOT_WEBHOOK_SECRET=process.env.BOT_WEBHOOK_SECRET;async function tg(m,p){const u=`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/${m}`;const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});return r.json();}
export default async function handler(req,res){if(req.query.secret!==BOT_WEBHOOK_SECRET) return res.status(403).send('forbidden');if(req.method!=='POST') return res.status(200).send('ok');const update=req.body;try{if(update.message&&update.message.text){const msg=update.message;const chatId=msg.chat.id;const text=(msg.text||'').trim();const u=msg.from;await supabaseAdmin.from('users').upsert({id:u.id,username:u.username||null,first_name:u.first_name||null,last_name:u.last_name||null});if(text==='/start'){await tg('sendMessage',{chat_id:chatId,text:'Welcome to VS Nursing Academy Quiz Bot!\nUse /quiz to start the latest quiz.\nUse /lang en|gu|hi to set your language.'});return res.status(200).send('ok');}
if(text.startsWith('/lang')){const parts=text.split(/\s+/);const lang=parts[1]?.toLowerCase();if(['en','gu','hi'].includes(lang)){await supabaseAdmin.from('users').update({preferred_lang:lang}).eq('id',u.id);await tg('sendMessage',{chat_id:chatId,text:`Language set to ${lang}.`});}else{await tg('sendMessage',{chat_id:chatId,text:'Usage: /lang en|gu|hi'});}return res.status(200).send('ok');}
if(text.startsWith('/quiz')){const parts=text.split(/\s+/);const tag=parts[1]?.trim();const { data: quiz } = await supabaseAdmin.from('quizzes').select('*').order('created_at',{ascending:false}).limit(1).single();if(!quiz){await tg('sendMessage',{chat_id:chatId,text:'No quizzes available yet.'});return res.status(200).send('ok');}
const { data: attemptRow } = await supabaseAdmin.from('attempts').insert([{quiz_id:quiz.id,user_id:u.id}]).select('*').single();await sendQuestion(chatId,quiz.id,attemptRow.id,1,tag,u.id);return res.status(200).send('ok');}}
if(update.callback_query){const cb=update.callback_query;const chatId=cb.message.chat.id;let payload={};try{payload=JSON.parse(cb.data);}catch{}const {attemptId,quizId,position,optionId,questionId}=payload;const { data: q } = await supabaseAdmin.from('questions').select('id,position,time_limit_seconds').eq('id',questionId).single();const { data: opt } = await supabaseAdmin.from('options').select('id,is_correct').eq('id',optionId).single();const correct=!!opt?.is_correct;await supabaseAdmin.from('answers').insert([{attempt_id:attemptId,question_id:questionId,option_id:optionId,is_correct:correct}]);if(correct){await supabaseAdmin.rpc('increment_attempt_score',{ p_attempt_id: attemptId });}await supabaseAdmin.rpc('advance_attempt_position',{ p_attempt_id: attemptId });await tg('answerCallbackQuery',{callback_query_id:cb.id,text:correct?'Correct ✅':'Wrong ❌'});const { data: attemptNow } = await supabaseAdmin.from('attempts').select('current_position,score,user_id').eq('id',attemptId).single();const { data: totalRows } = await supabaseAdmin.from('questions').select('id',{count:'exact',head:true}).eq('quiz_id',quizId);const total = totalRows?.length===0?0:totalRows?.length||(totalRows?.count??0);if(attemptNow.current_position>total){await supabaseAdmin.from('attempts').update({finished_at:new Date().toISOString()}).eq('id',attemptId);await updateStreak(attemptNow.user_id);await tg('sendMessage',{chat_id:chatId,text:`Finished! Your score: ${attemptNow.score} / ${total}`});}else{await sendQuestion(chatId,quizId,attemptId,attemptNow.current_position,null,attemptNow.user_id);}return res.status(200).send('ok');}
return res.status(200).send('ok');}catch(e){console.error(e);return res.status(200).send('ok');}}
async function sendQuestion(chatId,quizId,attemptId,position,tag,userId){const { data: user } = await supabaseAdmin.from('users').select('preferred_lang').eq('id',userId).single();const lang=user?.preferred_lang||'en';let { data: q } = await supabaseAdmin.from('questions').select('id,text,position,explanation,image_path,time_limit_seconds').eq('quiz_id',quizId).eq('position',position).single();if(!q){await tg('sendMessage',{chat_id:chatId,text:'Question not found.'});return;}if(tag){const { data: tags } = await supabaseAdmin.from('question_tags').select('question_id').eq('tag',tag);const allowed=new Set((tags||[]).map(t=>t.question_id));if(!allowed.has(q.id)){// find next tagged question at or after current
const { data: nextQ } = await supabaseAdmin.from('questions').select('id,text,position,explanation,image_path,time_limit_seconds').in('id', Array.from(allowed)).order('position',{ascending:true}).limit(1);if(nextQ&&nextQ[0]) q=nextQ[0];}
}
const { data: i18n } = await supabaseAdmin.from('question_i18n').select('text,explanation').eq('question_id',q.id).eq('lang',lang).maybeSingle?.() || {}; // safe
const text = i18n?.text || q.text;const expl = i18n?.explanation || q.explanation;const { data: opts } = await supabaseAdmin.from('options').select('id,text').eq('question_id',q.id);const keyboard={ inline_keyboard:(opts||[]).map(o=>[{ text:o.text, callback_data: JSON.stringify({attemptId,quizId,position:q.position,optionId:o.id,questionId:q.id}) }]) };
if(q.image_path){const { data: pub } = await supabaseAdmin.storage.from('questions').getPublicUrl(q.image_path);await tg('sendPhoto',{chat_id:chatId,photo:pub.publicUrl,caption:`Q${q.position}: ${text}`,reply_markup:keyboard});}
else{await tg('sendMessage',{chat_id:chatId,text:`Q${q.position}: ${text}`,reply_markup:keyboard});}
if(q.time_limit_seconds){setTimeout(()=>{}, q.time_limit_seconds*1000);} }
async function updateStreak(telegramUserId){const today=new Date().toISOString().slice(0,10);const { data: s } = await supabaseAdmin.from('streaks').select('*').eq('user_id',telegramUserId).single();if(!s){await supabaseAdmin.from('streaks').insert([{user_id:telegramUserId,last_played_date:today,current_streak:1,best_streak:1}]);return;}const prev=s.last_played_date;const y=new Date(Date.now()-24*3600*1000).toISOString().slice(0,10);let cur=1;let best=s.best_streak||1;if(prev===today){cur=s.current_streak;}// same day, no change
else if(prev===y){cur=s.current_streak+1;best=Math.max(best,cur);}else{cur=1;}await supabaseAdmin.from('streaks').update({last_played_date:today,current_streak:cur,best_streak:best}).eq('user_id',telegramUserId);}
